gravity-ui/page-constructor

- src/blocks/ContentLayout/__stories__/ContentLayout.stories.tsx
- src/blocks/ContentLayout/__stories__/data.json
- src/sub-blocks/Content/Content.scss
- src/sub-blocks/Content/Content.tsx
- src/sub-blocks/Content/__stories__/Content.stories.tsx
- src/sub-blocks/Content/__stories__/data.json
- styles/yfm.scss
Content component with size "s" has to have margin-bottom 8px between paragraphs. 
Change a little stories for Content and ContantLayout
> fix: change p margin for size s

- src/blocks/Media/__stories__/Media.stories.tsx
- src/blocks/Tabs/Tabs.tsx
- src/components/Media/Media.tsx
- src/components/Media/Video/Video.tsx
- src/components/ReactPlayer/ReactPlayer.tsx
- src/components/VideoBlock/VideoBlock.tsx
Fix video height  in Tabs when parent's height exists
> fix(Tabs): player video height

- src/components/Foldable/Foldable.scss
- src/components/Foldable/Foldable.tsx
- src/components/HeightCalculator/HeightCalculator.tsx
- src/hooks/useHeightCalculator.ts
Fixed issue: on mobile, the navigation can use wrong height or won't open at all.
Changes affect the PriceDetailed, Questions and MobileNavigation components.
> fix(Foldable): fix issues with content height calculation on resize

- src/containers/PageConstructor/components/ConstructorBlocks/ConstructorBlocks.tsx
- src/containers/PageConstructor/components/ConstructorItem/ConstructorItem.tsx
- src/containers/PageConstructor/components/ConstructorLoadable/ConstructorLoadable.tsx
> fix: move BlockIdContext.Provider inside ConstructorItem and ConstructorLoadable

- gulpfile.js
> fix: config gulpfile for tests

- src/blocks/Header/Header.scss
- src/containers/PageConstructor/__stories__/PageConstructor.stories.tsx
- src/demo/constants.ts
- src/models/navigation.ts
- src/navigation/__stories__/Navigation.stories.tsx
- src/navigation/__stories__/data.json
- src/navigation/components/Header/Header.scss
- src/navigation/components/Header/Header.tsx
Add new stories for navigation:
https://preview.gravity-ui.com/page-constructor/369/?path=/story/navigation-navigation--default-navigation
> feat: update header and navigation

- src/schema/validators/common.ts
> fix(Video): fix schema validator

- package-lock.json
- package.json
- src/components/Title/__stories__/Title.stories.tsx
- src/components/Title/__stories__/data.json
- Updated @doc-tools/transform to next major
- Fixed wrong prop name in Title.stories.tsx
> feat: update doc tools transform to next major

- src/components/Anchor/Anchor.tsx
- src/components/AnimateBlock/AnimateBlock.tsx
- src/components/AnimateBlock/__tests__/AnimateBlock.test.tsx
- src/components/Author/Author.tsx
- src/components/Author/__tests__/Author.test.tsx
- src/components/BackgroundImage/__tests__/BackgroundImage.test.tsx
- src/components/BlockBase/BlockBase.tsx
- src/components/BlockBase/__tests__/BlockBase.test.tsx
- src/components/Button/Button.tsx
- src/components/Button/__tests__/Button.test.tsx
- src/components/ButtonTabs/ButtonTabs.tsx
- src/components/ButtonTabs/__tests__/ButtonTabs.test.tsx
- src/components/Image/Image.tsx
- src/components/Title/TitleItem.tsx
- src/grid/Col/Col.tsx
- src/models/common.ts
- src/models/constructor-items/common.ts
BREAKING CHANGE: rename of props
> feat: rename data-qa props

- jest.config.js
to fix jest run added `tinygesture` to `transformIgnorePatterns`
> fix: add tinygesture module to transformIgnorePatterns

- src/models/constructor-items/sub-blocks.ts
- src/sub-blocks/BasicCard/BasicCard.scss
- src/sub-blocks/BasicCard/BasicCard.tsx
- src/sub-blocks/BasicCard/__stories__/BasicCard.stories.tsx
- src/sub-blocks/BasicCard/__stories__/data.json
- src/sub-blocks/BasicCard/schema.ts
* feat: add an icon position on the left side of a basic-card
> feat: add an icon position on the left side of a basic-card (#481)

- src/blocks/ExtendedFeatures/ExtendedFeatures.tsx
- src/blocks/PromoFeaturesBlock/PromoFeaturesBlock.tsx
- src/blocks/Questions/Questions.tsx
- src/sub-blocks/Content/ContentList/ContentList.tsx
- src/utils/blocks.ts
Closes https://github.com/gravity-ui/page-constructor/issues/483
> feat: correct usage of heading levels

- src/components/ButtonTabs/ButtonTabs.tsx
- src/models/constructor-items/common.ts
Closes https://github.com/gravity-ui/page-constructor/issues/487
> feat: add aria-current for tabs

- package-lock.json
- src/blocks/Slider/Arrow/Arrow.scss
- src/blocks/Slider/Arrow/Arrow.tsx
- src/blocks/Slider/Slider.scss
- src/blocks/Slider/Slider.tsx
- src/blocks/Slider/__tests__/Slider.test.tsx
- src/blocks/Slider/i18n/en.json
- src/blocks/Slider/i18n/index.ts
- src/blocks/Slider/i18n/ru.json
closes https://github.com/gravity-ui/page-constructor/issues/489
> feat: added labels for the Slider component

- src/blocks/Header/Header.scss
- src/blocks/Header/Header.tsx
- src/blocks/Header/__stories__/Header.mdx
- src/blocks/Header/__stories__/Header.stories.tsx
- src/blocks/Header/__stories__/data.json
- src/blocks/Header/schema.ts
- src/components/Table/Table.scss
- src/models/constructor-items/blocks.ts
- src/sub-blocks/PriceDetailed/PriceDescription/PriceDescription.scss
- styles/yfm.scss
1) In some installations we don't have fonts for font-weight: 500
So, i use the var to set font-weight, and override this var in regional config or project
2) Add new view for images and video in Header block. You can check storybook
> fix font weight

- .storybook/stories/documentation/Indents.mdx
- src/blocks/Form/Form.scss
- src/components/Author/Author.scss
- src/components/Media/DataLens/DataLens.scss
- src/components/Title/TitleItem.scss
- src/editor/components/EditBlock/EditBlock.scss
- src/editor/containers/Form/dynamic-form-custom.scss
- src/editor/dynamic-forms-custom/components/OneOfCustom/OneOfCustom.scss
- src/sub-blocks/HubspotForm/HubspotForm.scss
- src/sub-blocks/ImageCard/ImageCard.scss
- src/sub-blocks/PriceCard/PriceCard.scss
- src/sub-blocks/PriceDetailed/PriceDescription/PriceDescription.scss
- styles/mixins.scss
- styles/variables.scss
> feat: add indent4XS

- src/components/Media/Image/Image.tsx
- src/components/Media/Media.tsx
- src/models/constructor-items/common.ts
- src/schema/validators/common.ts
* feat: allow to disable image slider inside media component
> feat: allow to disable image slider inside media component (#887)

- src/components/IconWrapper/IconWrapper.scss
- src/components/IconWrapper/IconWrapper.tsx
fix: make BasicCard icon unshrinkable (v4)
> fix: make BasicCard icon unshrinkable (v4)

- src/sub-blocks/Content/Content.scss
fix: fixed Content links color (v4)
> fix: fixed Content links color (v4)

- src/models/constructor-items/sub-blocks.ts
- src/sub-blocks/ImageCard/ImageCard.tsx
- src/sub-blocks/ImageCard/__stories__/ImageCard.mdx
- src/sub-blocks/ImageCard/__stories__/ImageCard.stories.tsx
- src/sub-blocks/ImageCard/__stories__/data.json
- src/sub-blocks/ImageCard/schema.ts
https://github.com/gravity-ui/page-constructor/issues/875
> feat: ImageCard extension

- src/models/constructor-items/sub-blocks.ts
- src/sub-blocks/ImageCard/ImageCard.tsx
- src/sub-blocks/ImageCard/__stories__/ImageCard.mdx
- src/sub-blocks/ImageCard/__stories__/ImageCard.stories.tsx
- src/sub-blocks/ImageCard/__stories__/data.json
- src/sub-blocks/ImageCard/schema.ts
> feat: ImageCard extension (#876)

- src/blocks/Slider/Slider.tsx
- src/components/FullscreenImage/FullscreenImage.scss
- src/components/FullscreenImage/FullscreenImage.tsx
- src/components/Media/Image/Image.tsx
- src/components/Media/Media.scss
- src/components/Media/Media.tsx
This reverts commit eec646dd4173f37be952d477c2afc8fc8c82b41b.
> chore: Revert "feat: add media images fullscreen slider (#889)"

- src/components/IconWrapper/IconWrapper.scss
- src/components/IconWrapper/IconWrapper.tsx
- src/models/constructor-items/blocks.ts
- src/models/constructor-items/sub-blocks.ts
- src/schema/validators/common.ts
- src/sub-blocks/BackgroundCard/BackgroundCard.scss
- src/sub-blocks/BackgroundCard/BackgroundCard.tsx
- src/sub-blocks/BackgroundCard/schema.ts
- src/sub-blocks/BasicCard/BasicCard.scss
- src/sub-blocks/BasicCard/BasicCard.tsx
- src/sub-blocks/BasicCard/schema.ts
- src/sub-blocks/Content/Content.scss
- src/sub-blocks/Content/Content.tsx
- src/sub-blocks/Content/schema.ts
- src/sub-blocks/ImageCard/ImageCard.scss
- src/sub-blocks/ImageCard/ImageCard.tsx
- src/sub-blocks/ImageCard/__stories__/ImageCard.stories.tsx
- src/sub-blocks/ImageCard/__stories__/data.json
- src/sub-blocks/ImageCard/schema.ts
- src/sub-blocks/LayoutItem/LayoutItem.scss
- src/sub-blocks/LayoutItem/LayoutItem.tsx
- src/sub-blocks/LayoutItem/schema.ts
+ generalize contentPosition behavior for all cards
> feat(ImageCard): add contentPosition

- README.md
This reverts commit eb7f128ec65d6d9c8509558bd80530a9a5fc74a2.
> chore: Revert "chore: yaml format is already supported (#911)"

- README.md
- src/blocks/CardLayout/CardLayout.tsx
- src/blocks/Header/Header.tsx
- src/blocks/Slider/Slider.tsx
- src/components/AnimateBlock/AnimateBlock.tsx
- src/components/AnimateBlock/__tests__/AnimateBlock.test.tsx
- src/components/Author/Author.tsx
- src/components/BackgroundImage/BackgroundImage.tsx
- src/components/BalancedMasonry/BalancedMasonry.tsx
- src/components/BlockBase/__tests__/BlockBase.test.tsx
- src/components/ErrorWrapper/ErrorWrapper.tsx
- src/components/FileLink/FileLink.tsx
- src/components/Foldable/Foldable.tsx
- src/components/HTML/HTML.tsx
- src/components/Link/Link.tsx
- src/components/MediaBase/MediaBase.tsx
- src/components/RouterLink/RouterLink.tsx
- src/components/UnpublishedLabel/UnpublishedLabel.tsx
- src/containers/PageConstructor/Provider.tsx
- src/containers/PageConstructor/components/ConstructorBlock/ConstructorBlock.tsx
- src/containers/PageConstructor/components/ConstructorItem/ConstructorItem.tsx
- src/containers/PageConstructor/components/ConstructorRow/ConstructorRow.tsx
- src/context/locationContext/locationContext.ts
- src/grid/Col/Col.tsx
- src/grid/Grid/Grid.tsx
- src/models/constructor.ts
- src/models/index.ts
- src/models/react.ts
- test-utils/docs/README.md
> feat: remove custom withChildren

- src/navigation/components/Navigation/Navigation.tsx
> fix: hide header border when user scroll up the page

- src/blocks/SliderNew/Slider.scss
- src/blocks/SliderNew/useSlider.tsx
- safari-fix video
- dots classname
- fix autoplay disabling after user interactions
> fix: new slider styles

- .eslintrc
- package-lock.json
- package.json
- src/blocks/Questions/QuestionBlockItem/QuestionBlockItem.tsx
- src/components/DefaultVideo/DefaultVideo.tsx
- src/components/ImageBase/ImageBase.tsx
- src/components/Map/__stories__/ApiKeyInput.tsx
- src/components/OutsideClick/OutsideClick.tsx
- src/components/ReactPlayer/ReactPlayer.tsx
- src/components/Title/TitleItem.tsx
- src/components/VideoBlock/VideoBlock.tsx
- src/editor/components/AddBlock/AddBlock.tsx
- src/editor/components/EditBlock/EditBlock.tsx
- src/navigation/__stories__/CustomComponent/CustomComponent.tsx
- src/sub-blocks/PriceDetailed/PriceDetails/Details/List.tsx
> fix: enable a11y eslint rules

- src/text-transform/utils.ts
Use locale or lang
https://github.com/typograf/typograf/blob/dev/docs/api_localization.md
> fix: use languages ​​other than ru/en for Typograf

- src/sub-blocks/BackgroundCard/__stories__/BackgroundCard.stories.tsx
- src/sub-blocks/Content/Content.scss
> fix: support themes in list inside Content sub-block

- .github/workflows/pr-playwright-report.yml
after the merge the playwright report will be fixed
> fix: playwright actions

- .storybook/stories/documentation/Blocks.mdx
- .storybook/stories/documentation/Sub Blocks.mdx
- src/blocks/CardLayout/__stories__/CardLayout.mdx
- src/blocks/FoldableList/__stories__/FoldableList.mdx
- src/blocks/Form/__stories__/Form.mdx
- src/blocks/Info/__stories__/Info.mdx
- src/blocks/Map/__stories__/Map.mdx
- src/blocks/Questions/__stories__/Questions.mdx
- src/blocks/Slider/__stories__/Slider.mdx
- src/blocks/SliderNew/__stories__/Slider.mdx
- src/components/Button/README.md
- src/sub-blocks/Content/__stories__/Content.mdx
- src/sub-blocks/ImageCard/__stories__/ImageCard.mdx
- src/sub-blocks/LayoutItem/README.md
- src/sub-blocks/PriceDetailed/README.md
> chore: update docs stories links
