gravity-ui/page-constructor

src/text-transform/utils.ts
There are no rules for a phone mask in english, there are in russian and it works strangely. In russian it can turns out +7 (800-80) 0-11-11
=> fix: typograpf ru phone mask

package.json
Fixed peer dependencies because we uses React 17 everywhere
=> chore: fixed peer dependencies

src/components/Button/Button.scss, src/sub-blocks/Content/Content.scss, styles/root.scss
- Tabs in the dark theme has to have white button instead of black 
https://preview.yandexcloud.dev/page-constructor/89/?path=/story/blocks-tabs--default&globals=theme:dark;backgrounds.value:black;background:dark
- Content block (monochrome kight) in the dark theme has to have black button as in the light theme
https://preview.yandexcloud.dev/page-constructor/89/?path=/story/blocks-contentlayout--theme&globals=theme:dark;backgrounds.value:black;background:dark
=> fix: monochrome button theme

package-lock.json, package.json, src/containers/PageConstructor/__stories__/data.json, src/models/navigation.ts, src/navigation/components/NavigationItem/NavigationItem.tsx, src/navigation/components/NavigationItem/components/GithubButton/GithubButton.scss, src/navigation/components/NavigationItem/components/GithubButton/GithubButton.tsx
in the previous attempt, the component was used https://github.com/buttons/react-github-btn , but as it turned out, he has problems in the cjs build . Therefore, I wrote my own github button component, based on the experience of the finished component
=> feat: add github button in navigation

src/navigation/utils.ts
We can see this problem if we use `button` in rightItems in navigation and use Link from LocationContext
=> fix: cannot read stopPropagation of undefined in navigation utils

package-lock.json, package.json, src/components/ReactPlayer/ReactPlayer.tsx, src/components/ReactPlayer/utils.ts
=> feat: dropdown a ReactPlayer version

src/sub-blocks/BackgroundCard/BackgroundCard.tsx, src/sub-blocks/BackgroundCard/__stories__/BackgroundCard.stories.tsx, src/sub-blocks/BackgroundCard/__stories__/data.json, src/sub-blocks/BasicCard/__stories__/BasicCard.stories.tsx, src/sub-blocks/BasicCard/__stories__/data.json, styles/mixins.scss
Problem: If you hang a link on a card without a shadow or with an outline, then they become clickable, but a cursor-pointer does not appear on hover and the card does not fly up.
What to do: It is necessary to make them behave the same way as cards with a shadow. So that the card flies up on the hover + the cursor changes to a characteristic hover.
=> feat: add link animation for cards without shadow

.storybook/stories/documentation/Blocks.mdx, src/blocks/CardLayout/CardLayout.tsx, src/blocks/CardLayout/__stories__/CardLayout.stories.tsx, src/blocks/CardLayout/__stories__/data.json, src/blocks/FilterBlock/FilterBlock.scss, src/containers/PageConstructor/components/ConstructorBlock/ConstructorBlock.scss, src/containers/PageConstructor/components/ConstructorBlock/ConstructorBlock.tsx, src/models/constructor-items/blocks.ts, src/models/constructor.ts, src/text-transform/transformers.ts, styles/mixins.scss, styles/storybook/common.scss
- now `resetPadding` are deprecated
- add `indentTop`, and `indentBottom` for al blocks; sizes - `0 - xs - s - m - l - xl`
- add className prop for CardLayoutBlock
- now `--pc-first-block-indent` are deprecated
=> feat: add custom indent for all blocks, and add className prop for CardLayoutBlock

src/blocks/Header/Header.scss
- There is no need to add `margin-block-start` and `margin-block-end` for this parts. From this PR https://github.com/gravity-ui/page-constructor/pull/416/files
- there in no need to add `font-weight: normal` for div
- there is no need to add `font-size` because it is yfm-component and all styles applied for .yfm *
=> fix: remove unnecessary indents

src/navigation/components/NavigationItem/NavigationItem.scss, src/navigation/components/NavigationPopup/NavigationPopup.scss
_Dropdown navigation element_
The problem is that now the link is only the text and not the entire list item.
To see difference compare prod storybook and storybook from this branch.
=> fix: refactor indents for navigation popup

src/blocks/CardLayout/CardLayout.scss, src/blocks/CardLayout/CardLayout.tsx, src/blocks/CardLayout/__stories__/CardLayout.mdx, src/blocks/CardLayout/__stories__/CardLayout.stories.tsx, src/blocks/CardLayout/schema.ts, src/blocks/ContentLayout/schema.ts, src/components/Image/schema.ts, src/models/constructor-items/blocks.ts, src/schema/validators/common.ts, styles/mixins.scss
- Add border prop for card layout same as in the CardBase.
- Fix card layout schema validation for background
=> fix: card layout block background

src/blocks/ExtendedFeatures/__stories__/ExtendedFeatures.stories.tsx, src/blocks/Form/__stories__/Form.stories.tsx, src/blocks/Form/__stories__/data.json, src/blocks/Info/Info.tsx, src/blocks/Info/__stories__/Info.stories.tsx, src/blocks/Info/__stories__/data.json, src/blocks/Questions/Questions.tsx, src/blocks/Questions/__stories__/Questions.stories.tsx, src/blocks/Questions/__stories__/data.json, src/blocks/Tabs/TabsTextContent/TabsTextContent.tsx, src/blocks/Tabs/__stories__/Tabs.stories.tsx, src/blocks/Tabs/__stories__/data.json, src/models/constructor-items/blocks.ts, src/sub-blocks/BackgroundCard/BackgroundCard.tsx, src/sub-blocks/BackgroundCard/__stories__/BackgroundCard.stories.tsx, src/sub-blocks/BackgroundCard/__stories__/data.json, src/sub-blocks/LayoutItem/__stories__/LayoutItem.stories.tsx, src/sub-blocks/LayoutItem/__stories__/data.json
=> feat: support prop list in all content usecases

src/blocks/Questions/QuestionBlockItem/QuestionBlockItem.scss
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en 
Fixes: Link in Questions block available to clicked in all row width #923
=> fix: questionblock-link-clickable-all-rowwidth #923

src/components/ReactPlayer/ReactPlayer.tsx
For video with default controls player is not working properly.
On any click on control it starts video from beginning because of default props 
`customControlsType = CustomControlsType.WithMuteButton`
This fix changes this behaviour, the video starts from 0 seconds only if developer choose custom controls with mute button type
=> fix: video dont starts from beginning on click

src/components/ReactPlayer/ReactPlayer.tsx
Video change mute state on any click on player without custom controls, it looks like user clicks on video timeline and then his video is muted, although before that it was with sound
=> fix: video mute on video click

src/sub-blocks/Content/Content.scss
classname being wrong prevented the proper alignment of links in Content
`controlPosition: bottom` doesn't work for them
I can see that in the same file there are other instances of `#{$block}__link`. This classname doesn't exist in the component, so they do nothing, and either cause bugs, or should be removed entirely. Depending on the intention. I don't know how it should be, so only fixed the one I understand.
=> fix(Content): apply control-position: bottom to links

src/editor/components/AddBlock/AddBlock.tsx, src/editor/data/index.ts
Чиним проблему динамических импортов на vite
Что vite вообще отказывается нормально полифилить require и их динамические импорты с json 
В этом пр-е заменил require на import, json остались в отдельных чанках и идут через динамику, в cjs, остались require
Preview все никак не хотят заводится через динамику, поэтому пришлось запихнуть их в бандл, а так возможно можно потыкаться с lazy loading
=> fix: dynamic imports in vite prod build

styles/mixins.scss
When using `sass-loader@16` I got this error
```
Can't find stylesheet to import.  
@import 'node_modules/@gravity-ui/uikit/styles/mixins.scss';
node_modules/@gravity-ui/page-constructor/styles/mixins.scss 1:9                
```
So this is a small patch
=> Fix: fix import from node_modules 

README.md
=> chore: update readme about server utils and Vite

src/blocks/Header/Header.tsx
Just changed:
```tsx
type HeaderBlockFullProps = HeaderBlockProps & ClassNameProps;
```
To 
```tsx
export type HeaderBlockFullProps = HeaderBlockProps & ClassNameProps;
```
So it is now exported.
=> feat: added HeaderBlockFullProps to export
